## Load the dataset

In [18]:
# df = pd.read_csv('./data/Crop_recommendation.csv')
import pandas as pd
df = pd.read_csv('C:\\Users\\Admin\\Desktop\\Crop Recommendation\\Backend\\Crop_recommendation.csv')

In [19]:
df.tail()

N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

## Check wheather there is Objects or not

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


## Check the missings values of dataset

In [21]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

## Check the duplicates values of dataset

In [22]:
df.duplicated().sum()

np.int64(0)

## Check Each label name how many times 

In [23]:
df['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

## Categorical data

In [24]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['label'])

### To find Whch name name have which index value (i.e.., rice = 20,....)

In [25]:
df['label'].value_counts()

label
20    100
11    100
3     100
9     100
18    100
13    100
14    100
2     100
10    100
19    100
1     100
12    100
7     100
21    100
15    100
0     100
16    100
17    100
4     100
6     100
8     100
5     100
Name: count, dtype: int64

## Train the Data

In [26]:
from sklearn.model_selection import train_test_split


X = df.drop(columns='label', axis=1)
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)


## Scalling data 

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Check the Which type is fit for this model

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,GradientBoostingClassifier,AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier


from sklearn.metrics import accuracy_score

In [29]:
models = {
    'LogisticRegression':LogisticRegression(),
    'DecisionTreeClassifier': DecisionTreeClassifier(),
    'RandomForestClassifier':RandomForestClassifier(),
    'ExtraTreesClassifier':ExtraTreesClassifier(),
    'GradientBoostingClassifier':GradientBoostingClassifier(),
    'AdaBoostClassifier':AdaBoostClassifier(),
    'SupportVectorMachine': SVC(),
    'KNeighborsClassifier': KNeighborsClassifier(),

    
}
best_model = None
best_accuracy = 0.0
for name, model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)

    print(f'Model: {name} accuracy is: {accuracy}')
    print()

    if best_accuracy < accuracy:
        best_accuracy = accuracy
        best_model = model


print(f"Best Model is : {best_model}")

Model: LogisticRegression accuracy is: 0.9636363636363636

Model: DecisionTreeClassifier accuracy is: 0.9886363636363636

Model: RandomForestClassifier accuracy is: 0.9931818181818182

Model: ExtraTreesClassifier accuracy is: 0.9886363636363636

Model: GradientBoostingClassifier accuracy is: 0.9818181818181818

Model: AdaBoostClassifier accuracy is: 0.14545454545454545

Model: SupportVectorMachine accuracy is: 0.9681818181818181

Model: KNeighborsClassifier accuracy is: 0.9568181818181818

Best Model is : RandomForestClassifier()


## Random Forest Classifier

In [30]:
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9931818181818182


In [31]:
X_test

array([[ 1.34934948, -1.0960582 , -0.02225388, ...,  1.05232434,
        -0.37619899, -1.38984486],
       [ 1.26889319, -1.36698971,  0.05607978, ...,  0.67956909,
        -0.28013033, -0.96895253],
       [ 0.22296144,  0.25859933,  0.01691295, ...,  0.98974316,
         0.60209743,  0.22056087],
       ...,
       [ 1.88572474, -0.19295318, -0.62933977, ...,  0.35134079,
         1.61311363, -0.54905776],
       [ 1.75163092, -0.04243567, -0.57058952, ...,  0.1731198 ,
        -0.46741089, -0.64767698],
       [-1.22525175,  0.43922034, -0.55100611, ..., -1.74645651,
        -0.45817577,  0.95946086]], shape=(440, 7))

#### If we directly enter the Input values which present in data set means it show array[0].., because we use "Standard Scaler"

In [32]:
rfc.predict([[104,	18	,30,	23.603016,	60.396475	,6.779833	,140.937041]])

array([0])

#### It is very diffict to enter the scaled inputs every time

In [33]:
rfc.predict([[1.34934948, -1.0960582 , -0.02225388, 1.65234,  1.05232434,
        -0.37619899, -1.38984486]])

array([15])

## To convert scaled inputs to Normal inputs

In [34]:
import numpy as np

def predict_from_raw(raw_input):
    # Convert to NumPy array and reshape if needed
    raw_input = np.array(raw_input).reshape(1, -1)  
    
    # Scale the input using the fitted scaler
    scaled_input = sc.transform(raw_input)
    
    # Predict using the trained model
    prediction = rfc.predict(scaled_input)
    
    return prediction


# Get prediction
output = predict_from_raw([104	,18	,30	,23.603016	,60.396475	,6.779833	,140.937041])
print("Predicted Output:", output)


Predicted Output: [5]


C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


## To convert Index value a Normal Output

In [35]:
original_text_label = label_encoder.inverse_transform([output])
print("Original Text Label:", original_text_label)


Original Text Label: ['coffee']


C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Pickle

In [36]:
import pickle

# Save the model
with open("model.pkl", "wb") as model_file:
    pickle.dump(rfc, model_file)

# Save the scaler
with open("scaler.pkl", "wb") as scaler_file:
    pickle.dump(sc, scaler_file)

# Save the label encoder
with open("label_encoder.pkl", "wb") as le_file:
    pickle.dump(label_encoder, le_file)
